"use client";

// import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import { lightTheme, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { config } from "@/lib/wagmi";
import localFont from "next/font/local";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const clashGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/ClashGrotesk-Extralight.otf",
      weight: "200",
    },
    {
      path: "../public/fonts/ClashGrotesk-Light.otf",
      weight: "300",
    },
    {
      path: "../public/fonts/ClashGrotesk-Regular.otf",
      weight: "400",
    },
    {
      path: "../public/fonts/ClashGrotesk-Medium.otf",
      weight: "500",
    },
    {
      path: "../public/fonts/ClashGrotesk-Semibold.otf",
      weight: "600",
    },
    {
      path: "../public/fonts/ClashGrotesk-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-clash-grotesk",
});

const client = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashGrotesk.variable}  antialiased`}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitProvider
              modalSize="compact"
              theme={lightTheme({
                accentColor: "#c28446",
                accentColorForeground: "white",
                borderRadius: "large",
                fontStack: "system",
                overlayBlur: "small",
              })}
            >
              {children}
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
